# Generated by Django 2.1.2 on 2018-11-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
